### ISSUE TITLE
What is the main branch?

### ISSUE THREAD

**Issue by MaxG87** [cilynx/rtl88x2bu#47]
I am trying to contribute my work on DWA-182 to this project. I am a bit confused which branch is the main one. Both, 5.6.1_30... and 5.6.1.6 seem to be actively maintained. I could not figure out the differences :-(. Could you please point out?

**Comment by cilynx** [comment]
Because of the way upstream works, there kindof isn't one =(

Every 3-6 months, a new version comes out from the vendor upstream, but they don't pay attention to this repo so several of the fixes / improvements here aren't a part of the new versions.  When new versions are released, I create a new branch starting with that clean upstream source and as I have time I apply the various patches from the prior version -- with modifications as necessary.  

Once all of the appropriate patches have been applied, I promote that version branch to be `default`.  Today, `5.6.1` is the most recent branch that has all of the patches.  The `5.6.1.6` branch has a newer upstream source, but does not yet have all of the patches applied.
